name: Björn Tillenius
meta_description: "Björn Tillenius"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
logo: false
paginate: 15
permalink: /blog/:year/:month/:day/:title
baseurl: /

# Details for the RSS feed generator
url:            'https://tillenius.me'
author:         'Björn Tillenius'
