name: Björn Tillenius
description: Blogging about stuffs
meta_description: "Björn Tillenius, Blogging about stuffs"

markdown: redcarpet
pygments: true
logo: false
paginate: 15
permalink: /blog/:year/:month/:day/:title
baseurl: /

# Details for the RSS feed generator
url:            'http://tillenius.me/'
author:         'Björn Tillenius'
